404 page
Sillor/timewise-client pull request #26
Opened 2024-01-10 22:08 UTC by AlissonRoss

Super barebones/simple 404 page for now

2024-01-11 00:54 UTC, nlawler1737 approved these changes
looks good!

2024-01-11 23:00 UTC, lclemente225 submitted a review, later dismissed
Looks good

2024-01-13 00:41 UTC, nlawler1737 requested changes
The path to broken.png should be "../../assets/broken.png".

2024-01-16 21:57 UTC, AlissonRoss commented
Updated the 404 Page to the changes in main and added it to the sidebar and router. 

iPhone 11 Pro 
![image](https://github.com/Sillor/timewise-client/assets/25699172/e08e88e0-83d5-4b0f-beb0-241a3cfac24e)
Galaxy Note 20
![image](https://github.com/Sillor/timewise-client/assets/25699172/b932eaf0-a0d2-45b1-a663-6ab890a891e7)
Desktop:
![image](https://github.com/Sillor/timewise-client/assets/25699172/4ebb16ee-e52c-4e1a-bd32-fb10b5fa6732)

2024-01-16 21:58 UTC, AlissonRoss commented
> The path to broken.png should be "../../assets/broken.png".

This should be fixed now

2024-01-16 22:03 UTC, nlawler1737 commented on src/timetracker/pages/404-page/404-page.jsx
> +            <div className="flex flex-col items-center">
I would also add text-center so it doesn't default to left aligned on smaller screens

2024-01-16 22:03 UTC, nlawler1737 submitted a review, later dismissed
looks good

2024-01-16 22:33 UTC, lclemente225 submitted a review, later dismissed
Looks good, I just want to note that we should have a redirect in the config for this page when the page returns a 404 code.

2024-01-16 23:37 UTC, nlawler1737 approved these changes

2024-01-16 23:57 UTC, lclemente225 commented on src/timetracker/components/navbar/Sidebar.jsx
Question: I noticed that the 404 page is listed in the sidebar. Will it be there on deployment?

2024-01-17 00:02 UTC, lclemente225 commented on src/main.jsx
> +          },
Question: I don't have experience with Browser Router, but I was wondering if this path of "/*" for the PageNotFound component was fine to use.

2024-01-17 00:06 UTC, lclemente225 approved these changes
Looks good

2024-01-17 00:07 UTC, AlissonRoss commented on src/timetracker/components/navbar/Sidebar.jsx
I added it to main.jsx as a route. Hopefully this helps

2024-01-17 00:07 UTC, merged