Feature/confirm reset password component
Sillor/timewise-client pull request #37
Opened 2024-01-12 21:53 UTC by kimbencinas

• created the confirm reset password page
• responsive

2024-01-12 22:30 UTC, AlissonRoss commented
![image](https://github.com/Sillor/timewise-client/assets/25699172/0b751671-52bd-4b94-a8b6-968863e55210)
Path issue. Let me know when it's resolved

2024-01-12 23:58 UTC, AlissonRoss approved these changes
Beautiful work 
![image](https://github.com/Sillor/timewise-client/assets/25699172/a7170c56-be37-419e-a435-0849137940a8)

2024-01-13 00:22 UTC, AlissonRoss commented
![image](https://github.com/Sillor/timewise-client/assets/25699172/53b21668-bc71-4841-bb8d-0f6faf989e30)
You can use the form input that Nolan made for the text fields that have the eye password toggle. 
![image](https://github.com/Sillor/timewise-client/assets/25699172/259dbb47-047b-42a0-ba8f-0903dcff69c2)

2024-01-13 00:29 UTC, nlawler1737 requested changes
fix link tag

2024-01-13 00:29 UTC, nlawler1737 commented on src/timetracker/pages/confirm-password-reset/ConfirmPasswordReset.jsx
> +                        <a href="./SignUp" className="ml-1 text-blue-500 underline"> Sign Up</a>
Use Link from react-router instead of an "a" tag, also the link should go to "/register".

2024-01-13 00:39 UTC, wyzhaobvt commented on src/timetracker/pages/confirm-password-reset/ConfirmPasswordReset.jsx
Great Job! Also, adding the passwordEye icon in the input field could be better. The icon component can be found in the form-component folder which is inside the components folder.

2024-01-13 00:40 UTC, wyzhaobvt commented on src/timetracker/pages/confirm-password-reset/ConfirmPasswordReset.jsx
> +                <form>
Great Job! Also, adding the passwordEye icon in the input fields could be better. The icon component can be found in the form-component folder which is inside the components folder.

2024-01-16 22:44 UTC, nlawler1737 commented
There is a FromInput component that handles password hiding for you.

2024-01-16 23:14 UTC, Sillor approved these changes
Looks good!

2024-01-16 23:16 UTC, AlissonRoss approved these changes
Sweet!

2024-01-16 23:17 UTC, nlawler1737 approved these changes
looks good

2024-01-16 23:17 UTC, merged