#2 made basic layout
Sillor/timewise-client pull request #9
Opened 2024-01-08 23:35 UTC by GustavoAcosta02

Made basic-ish layout, still needs more tweaks to it though

2024-01-10 00:16 UTC, lclemente225 approved these changes
Feedback: I noticed that you added CSS to the App.css file. It works for now, however, I see an issue if other people use the same class. It might be useful for debugging if you have CSS folders that pertain to the component that they are styling.

2024-01-10 03:45 UTC, Sillor commented
Please pull from `main` first and resolve the merge conflict.

2024-01-11 23:01 UTC, lclemente225 approved these changes
Looks good

2024-01-17 21:26 UTC, Sillor requested changes

2024-01-17 21:26 UTC, Sillor commented on package-lock.json
Remove this file

2024-01-17 21:26 UTC, Sillor commented on src/timetracker/components/login/Login.css
Most of this can be implemented with tailwind, why not use it?

2024-01-18 21:38 UTC, AlissonRoss commented
Work on responsiveness for mobile viewport
Other than that, Beautiful work

2024-01-19 21:28 UTC, AlissonRoss approved these changes
![image](https://github.com/Sillor/timewise-client/assets/25699172/571be37f-e41c-44a5-acf7-dd031506d636)
Wonderful! I am approving this

2024-01-19 22:11 UTC, Sillor approved these changes
Looks good 👍

2024-01-19 22:12 UTC, merged